Footer styling fix
SSWConsulting/SSW.CodeAuditor pull request #177
Opened 2021-03-26 00:42 UTC by tombui99

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/67776356/112560936-4c027e80-8e28-11eb-8444-5c5459fa1df1.png">

**Figure: Fixed footer with new styling**

2021-03-26 05:17 UTC, bfabiny approved these changes

2021-03-26 15:47 UTC, tiagov8 requested changes
Hi @tombui99,

I think you missed:

> This is caused by an 8px padding added to the body.
> <img width="237" alt="Screen Shot 2021-03-25 at 3 51 49 PM" src="https://user-images.githubusercontent.com/12601228/112657311-87448380-8e0f-11eb-8f8d-7613e4b2b37c.png">
> 1. Please remove that 8px padding from body CSS

This should be done at https://github.com/SSWConsulting/SSW.CodeAuditor/blob/91b4811e8aa2f200a9989929f8e8564ec664d9d7/ui/public/global.css
<img width="934" alt="Screen Shot 2021-03-26 at 8 46 39 AM" src="https://user-images.githubusercontent.com/12601228/112657606-d4c0f080-8e0f-11eb-9b4a-9800e09042c9.png">

PS. I could do it myself, but I guess it's better to keep all these changes in the same PR?

2021-03-28 23:51 UTC, tombui99 commented
> Hi @tombui99,
> 
> I think you missed:
> 
> > This is caused by an 8px padding added to the body.
> > <img alt="Screen Shot 2021-03-25 at 3 51 49 PM" width="237" src="https://user-images.githubusercontent.com/12601228/112657311-87448380-8e0f-11eb-8f8d-7613e4b2b37c.png">
> > 
> > 1. Please remove that 8px padding from body CSS
> 
> This should be done at https://github.com/SSWConsulting/SSW.CodeAuditor/blob/91b4811e8aa2f200a9989929f8e8564ec664d9d7/ui/public/global.css
> <img alt="Screen Shot 2021-03-26 at 8 46 39 AM" width="934" src="https://user-images.githubusercontent.com/12601228/112657606-d4c0f080-8e0f-11eb-9b4a-9800e09042c9.png">
> 
> PS. I could do it myself, but I guess it's better to keep all these changes in the same PR?

Hi @tiagov8 

Done - I have fixed accordingly

2021-03-29 00:19 UTC, bfabiny approved these changes

2021-03-29 01:01 UTC, merged